# render.yml

services:
  - name: telegram-bot
    type: private
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m FallenRobot
    envVars:
      - key: TOKEN
        sync: false # Store the token securely in the Render dashboard
      - key: WEBHOOK_URL
        sync: false # Optional: Store your webhook URL securely
    autoDeploy: true # Automatically deploy new commits to the branch
